// SPDX-License-Identifier: BSD-3-Clause-Clear
//
// Auto-generated by riscv-unified-db (udb-gen cfg-svh-header)
// Config: bonato-2
//
// Define conventions:
//   Extensions:           `define NAME_SUPPORTED and `define NAMEverPver_SUPPORTED
//   Boolean params:       `define UDB_NAME           (present when true, absent when false)
//   Integer params:       `define UDB_NAME value     and `define UDB_NAME_<value>
//   Enum (string) params: `define UDB_NAME_VALUE     (value sanitized to uppercase identifier)
//   Boolean arrays:       `define UDB_NAME_<index>   (one per true element)
//   Integer arrays:       `define UDB_NAME_<value>   (one per unique element, sorted)
//   String arrays:        `define UDB_NAME_<VALUE>   (one per unique element, sanitized)

`ifndef UDB_CFG_BONATO_2_SVH
`define UDB_CFG_BONATO_2_SVH

// Implemented extensions
`define I_SUPPORTED
`define I2P1_SUPPORTED
`define SM_SUPPORTED
`define SM1P12P0_SUPPORTED

// Configuration parameters
`define UDB_CONFIG_PTR_ADDRESS 32'h0
`define UDB_CONFIG_PTR_ADDRESS_0
`define UDB_HPM_COUNTER_EN_3
`define UDB_HPM_COUNTER_EN_4
`define UDB_HPM_COUNTER_EN_5
`define UDB_HPM_COUNTER_EN_6
`define UDB_HPM_COUNTER_EN_7
`define UDB_HPM_COUNTER_EN_8
`define UDB_HPM_COUNTER_EN_9
`define UDB_HPM_COUNTER_EN_10
`define UDB_HPM_COUNTER_EN_11
`define UDB_HPM_COUNTER_EN_12
`define UDB_MISALIGNED_LDST
`define UDB_MISALIGNED_LDST_EXCEPTION_PRIORITY_LOW
`define UDB_MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE 32'h0
`define UDB_MISALIGNED_MAX_ATOMICITY_GRANULE_SIZE_0
`define UDB_MISALIGNED_SPLIT_STRATEGY_CUSTOM
`define UDB_MTVAL_WIDTH 32'h20
`define UDB_MTVAL_WIDTH_32
`define UDB_MTVEC_ACCESS_RW
`define UDB_MTVEC_BASE_ALIGNMENT_VECTORED 32'h100
`define UDB_MTVEC_BASE_ALIGNMENT_VECTORED_256
`define UDB_MTVEC_ILLEGAL_WRITE_BEHAVIOR_CUSTOM
`define UDB_MTVEC_MODES_1
`define UDB_MXLEN 32'h20
`define UDB_MXLEN_32
`define UDB_M_MODE_ENDIANNESS_LITTLE
`define UDB_NUM_PMP_ENTRIES 32'h0
`define UDB_NUM_PMP_ENTRIES_0
`define UDB_PHYS_ADDR_WIDTH 32'h20
`define UDB_PHYS_ADDR_WIDTH_32
`define UDB_PMA_GRANULARITY 32'h2
`define UDB_PMA_GRANULARITY_2
`define UDB_PRECISE_SYNCHRONOUS_EXCEPTIONS
`define UDB_VENDOR_ID_BANK 32'h0
`define UDB_VENDOR_ID_BANK_0
`define UDB_VENDOR_ID_OFFSET 32'h0
`define UDB_VENDOR_ID_OFFSET_0

`endif // UDB_CFG_BONATO_2_SVH
